apiVersion: v1
kind: Pod
metadata:
  name: test-nfs-volume
spec:
  containers:
    - name: test-nfs
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: nfs-volumes   #被挂载 nfs volume 的
          mountPath: /usr/share/nginx/html   #容器中挂载的位置
    - name: test-tomcat
      image: tomcat
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - name: nfs-volumes1
          mountPath: /test
  volumes:
    - name: nfs-volumes   #nfs volume 名称
      nfs:
        path: /opt/test    #nfs 定义共享的文件位置
        server: 127.0.0.1  #nfs服务的ip地址
    - name: nfs-volumes1
      nfs:
        path: /opt/test1
        server: 127.0.0.1






